package com.fishit.player.tools.docgen

import java.io.File
import java.time.LocalDate

/**
 * Generates architecture diagrams (Mermaid/PlantUML) from module structure
 * and annotated pipeline components.
 *
 * Generates:
 * - docs/architecture/diagrams/pipeline-flow.md (Mermaid)
 * - docs/architecture/diagrams/c4-containers.puml (PlantUML)
 * - docs/architecture/diagrams/layer-boundaries.md (Mermaid)
 */
class DiagramGenerator(private val rootDir: File) {

    fun generate() {
        val outputDir = File(rootDir, "docs/architecture/diagrams")
        outputDir.mkdirs()

        generatePipelineFlow(outputDir)
        generateLayerBoundaries(outputDir)
        generateC4Containers(outputDir)
    }

    /**
     * Generates a sequence diagram showing the Xtream pipeline flow.
     */
    private fun generatePipelineFlow(outputDir: File) {
        val output = File(outputDir, "pipeline-flow.md")
        output.writeText(
            buildString {
                appendLine("# Pipeline Flow")
                appendLine()
                appendLine("**Generated on ${LocalDate.now()} — DO NOT EDIT MANUALLY**")
                appendLine()
                appendLine("> Regenerate with: `./gradlew :tools:doc-generator:run --args=\"--diagrams\"`")
                appendLine()
                appendLine("## Xtream Catalog Sync Flow")
                appendLine()
                appendLine("```mermaid")
                appendLine("sequenceDiagram")
                appendLine("    participant W as CatalogSyncWorker")
                appendLine("    participant P as XtreamCatalogPipeline")
                appendLine("    participant T as XtreamApiClient")
                appendLine("    participant M as XtreamMapper")
                appendLine("    participant N as MetadataNormalizer")
                appendLine("    participant DB as NxCatalogWriter")
                appendLine()
                appendLine("    Note over W,DB: Scan Phase")
                appendLine("    W->>P: startSync(account, categories)")
                appendLine("    P->>T: fetchVodStreams(category)")
                appendLine("    T-->>P: XtreamVodApiDto[]")
                appendLine("    P->>M: mapToRaw(dto)")
                appendLine("    M-->>P: RawMediaMetadata[]")
                appendLine()
                appendLine("    Note over W,DB: Normalization Phase")
                appendLine("    P->>N: normalize(raw)")
                appendLine("    N-->>P: NormalizedMediaMetadata")
                appendLine()
                appendLine("    Note over W,DB: Persistence Phase")
                appendLine("    P->>DB: ingest(normalized)")
                appendLine("    DB-->>P: IngestResult")
                appendLine("    P-->>W: SyncResult(added, updated, errors)")
                appendLine("```")
                appendLine()
                appendLine("## Telegram Pipeline Flow")
                appendLine()
                appendLine("```mermaid")
                appendLine("sequenceDiagram")
                appendLine("    participant W as CatalogSyncWorker")
                appendLine("    participant P as TelegramCatalogPipeline")
                appendLine("    participant T as TelegramClient")
                appendLine("    participant M as TelegramMediaMapper")
                appendLine("    participant N as MetadataNormalizer")
                appendLine("    participant DB as NxCatalogWriter")
                appendLine()
                appendLine("    W->>P: startSync(account, channels)")
                appendLine("    P->>T: getHistory(channelId)")
                appendLine("    T-->>P: TgMessage[]")
                appendLine("    P->>M: mapToRaw(message)")
                appendLine("    M-->>P: RawMediaMetadata[]")
                appendLine("    P->>N: normalize(raw)")
                appendLine("    N-->>P: NormalizedMediaMetadata")
                appendLine("    P->>DB: ingest(normalized)")
                appendLine("    DB-->>P: IngestResult")
                appendLine("```")
            },
        )
        println("   ✅ Generated: ${output.relativeTo(rootDir).path}")
    }

    /**
     * Generates a diagram showing layer boundaries and allowed dependencies.
     */
    private fun generateLayerBoundaries(outputDir: File) {
        val output = File(outputDir, "layer-boundaries.md")
        output.writeText(
            buildString {
                appendLine("# Layer Boundaries")
                appendLine()
                appendLine("**Generated on ${LocalDate.now()} — DO NOT EDIT MANUALLY**")
                appendLine()
                appendLine("> Regenerate with: `./gradlew :tools:doc-generator:run --args=\"--diagrams\"`")
                appendLine()
                appendLine("## Architecture Layers")
                appendLine()
                appendLine("```mermaid")
                appendLine("graph TD")
                appendLine("    subgraph UI[\"UI Layer\"]")
                appendLine("        feature_home[\"feature:home\"]")
                appendLine("        feature_library[\"feature:library\"]")
                appendLine("        feature_detail[\"feature:detail\"]")
                appendLine("        feature_settings[\"feature:settings\"]")
                appendLine("    end")
                appendLine()
                appendLine("    subgraph Domain[\"Domain Layer\"]")
                appendLine("        core_home_domain[\"core:home-domain\"]")
                appendLine("        core_library_domain[\"core:library-domain\"]")
                appendLine("        core_detail_domain[\"core:detail-domain\"]")
                appendLine("    end")
                appendLine()
                appendLine("    subgraph Data[\"Data Layer\"]")
                appendLine("        infra_data_nx[\"infra:data-nx\"]")
                appendLine("        infra_data_xtream[\"infra:data-xtream\"]")
                appendLine("        infra_data_telegram[\"infra:data-telegram\"]")
                appendLine("    end")
                appendLine()
                appendLine("    subgraph Pipeline[\"Pipeline Layer\"]")
                appendLine("        pipeline_xtream[\"pipeline:xtream\"]")
                appendLine("        pipeline_telegram[\"pipeline:telegram\"]")
                appendLine("    end")
                appendLine()
                appendLine("    subgraph Transport[\"Transport Layer\"]")
                appendLine("        infra_transport_xtream[\"infra:transport-xtream\"]")
                appendLine("        infra_transport_telegram[\"infra:transport-telegram\"]")
                appendLine("    end")
                appendLine()
                appendLine("    subgraph Core[\"Core Model\"]")
                appendLine("        core_model[\"core:model\"]")
                appendLine("        core_persistence[\"core:persistence\"]")
                appendLine("    end")
                appendLine()
                appendLine("    UI --> Domain")
                appendLine("    Domain --> Data")
                appendLine("    Data --> Core")
                appendLine("    Pipeline --> Transport")
                appendLine("    Pipeline --> Core")
                appendLine("    Transport --> Core")
                appendLine()
                appendLine("    style UI fill:#4CAF50,color:#fff")
                appendLine("    style Domain fill:#2196F3,color:#fff")
                appendLine("    style Data fill:#FF9800,color:#fff")
                appendLine("    style Pipeline fill:#9C27B0,color:#fff")
                appendLine("    style Transport fill:#F44336,color:#fff")
                appendLine("    style Core fill:#607D8B,color:#fff")
                appendLine("```")
                appendLine()
                appendLine("## Forbidden Dependencies")
                appendLine()
                appendLine("| Layer | MUST NOT Import From |")
                appendLine("|-------|---------------------|")
                appendLine("| Pipeline | Persistence, Data, Playback, UI |")
                appendLine("| Transport | Pipeline, Data, Playback, UI, Persistence |")
                appendLine("| Data | Pipeline DTOs (TelegramMediaItem, XtreamVodItem) |")
                appendLine("| Playback | Pipeline DTOs |")
                appendLine("| UI/Feature | Obx*, Pipeline DTOs, Transport |")
            },
        )
        println("   ✅ Generated: ${output.relativeTo(rootDir).path}")
    }

    /**
     * Generates a C4 Container diagram in PlantUML format.
     */
    private fun generateC4Containers(outputDir: File) {
        val output = File(outputDir, "c4-containers.puml")
        output.writeText(
            buildString {
                appendLine("@startuml C4 Container Diagram")
                appendLine("!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml")
                appendLine()
                appendLine("' Generated on ${LocalDate.now()} - DO NOT EDIT MANUALLY")
                appendLine("' Regenerate: ./gradlew :tools:doc-generator:run --args=\"--diagrams\"")
                appendLine()
                appendLine("LAYOUT_WITH_LEGEND()")
                appendLine()
                appendLine("System_Boundary(app, \"FishIT-Player v2\") {")
                appendLine()
                appendLine("    ' UI Layer")
                appendLine("    Container(feature_home, \"Home\", \"Jetpack Compose\", \"Browse catalog, continue watching\")")
                appendLine("    Container(feature_library, \"Library\", \"Jetpack Compose\", \"Media library with filters\")")
                appendLine("    Container(feature_detail, \"Detail\", \"Jetpack Compose\", \"Work detail + sources\")")
                appendLine("    Container(feature_settings, \"Settings\", \"Jetpack Compose\", \"App configuration\")")
                appendLine()
                appendLine("    ' Domain Layer")
                appendLine("    Container(core_domain, \"Domain\", \"Kotlin\", \"Use cases, orchestration\")")
                appendLine()
                appendLine("    ' Data Layer")
                appendLine("    Container(infra_data_nx, \"NX Data\", \"ObjectBox\", \"SSOT repository layer\")")
                appendLine()
                appendLine("    ' Pipeline Layer")
                appendLine("    Container(pipeline_xtream, \"Xtream Pipeline\", \"Kotlin\", \"Catalog sync from Xtream\")")
                appendLine("    Container(pipeline_telegram, \"Telegram Pipeline\", \"Kotlin\", \"Catalog sync from Telegram\")")
                appendLine()
                appendLine("    ' Transport Layer")
                appendLine("    Container(transport_xtream, \"Xtream Transport\", \"OkHttp\", \"Xtream API client\")")
                appendLine("    Container(transport_telegram, \"Telegram Transport\", \"TDLib\", \"Telegram client\")")
                appendLine()
                appendLine("    ' Player")
                appendLine("    Container(player, \"Internal Player\", \"Media3\", \"Video/audio playback\")")
                appendLine()
                appendLine("    ' Core")
                appendLine("    ContainerDb(persistence, \"ObjectBox DB\", \"ObjectBox\", \"NX_Work entities\")")
                appendLine("    Container(core_model, \"Core Model\", \"Kotlin\", \"Shared types, enums\")")
                appendLine("}")
                appendLine()
                appendLine("' External Systems")
                appendLine("System_Ext(xtream_api, \"Xtream API\", \"VOD/Series/Live provider\")")
                appendLine("System_Ext(telegram_api, \"Telegram API\", \"TDLib-based media channels\")")
                appendLine("System_Ext(tmdb, \"TMDB API\", \"Movie/TV metadata enrichment\")")
                appendLine()
                appendLine("' Relationships")
                appendLine("Rel(feature_home, core_domain, \"uses\")")
                appendLine("Rel(core_domain, infra_data_nx, \"queries\")")
                appendLine("Rel(pipeline_xtream, transport_xtream, \"fetches via\")")
                appendLine("Rel(pipeline_telegram, transport_telegram, \"fetches via\")")
                appendLine("Rel(pipeline_xtream, infra_data_nx, \"writes to\")")
                appendLine("Rel(pipeline_telegram, infra_data_nx, \"writes to\")")
                appendLine("Rel(infra_data_nx, persistence, \"stores in\")")
                appendLine("Rel(transport_xtream, xtream_api, \"HTTP\")")
                appendLine("Rel(transport_telegram, telegram_api, \"TDLib\")")
                appendLine("Rel(core_domain, tmdb, \"enriches from\")")
                appendLine("Rel(player, transport_xtream, \"streams from\")")
                appendLine("Rel(player, transport_telegram, \"streams from\")")
                appendLine()
                appendLine("@enduml")
            },
        )
        println("   ✅ Generated: ${output.relativeTo(rootDir).path}")
    }
}
