#!/usr/bin/env bash
# Sync agent rules from canonical source to distribution files

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

CANONICAL="$REPO_ROOT/docs/meta/AGENT_RULES_CANONICAL.md"
AGENTS="$REPO_ROOT/AGENTS.md"
COPILOT="$REPO_ROOT/.github/copilot-instructions.md"

if [[ ! -f "$CANONICAL" ]]; then
    echo "Error: Canonical source not found: $CANONICAL"
    exit 1
fi

echo "Syncing agent rules from canonical source..."

# Generate header (identical for both files)
HEADER='# AGENTS – FishIT-Player v2 (architecture/v2-bootstrap)

> **⚠️ GENERATED FILE - DO NOT EDIT MANUALLY**
> 
> This file is automatically generated from `docs/meta/AGENT_RULES_CANONICAL.md`.
> To make changes, edit the canonical source and regenerate this file.
> CI checks ensure files remain synchronized.

'

# Generate AGENTS.md
echo -n "$HEADER" > "$AGENTS"
tail -n +2 "$CANONICAL" >> "$AGENTS"

# Generate .github/copilot-instructions.md
echo -n "$HEADER" > "$COPILOT"
tail -n +2 "$CANONICAL" >> "$COPILOT"

echo "✓ Successfully synced:"
echo "  - $AGENTS"
echo "  - $COPILOT"
echo ""
echo "Files are now byte-identical."
