name: CI (manual: audit/lint/unit)

on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build-unit-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - uses: android-actions/setup-android@v3

      - uses: gradle/actions/setup-gradle@v3
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Install ripgrep (rg)
        run: |
          if ! command -v rg >/dev/null 2>&1; then
            sudo apt-get update
            sudo apt-get install -y ripgrep
          fi

      - name: TV Focus/DPAD Audit
        run: bash tools/audit_tv_focus.sh ci

      - name: Fix gradlew permissions
        run: |
          chmod +x ./gradlew
          sed -i 's/\r$//' gradlew || true

      - name: Build + Unit Tests
        env:
          HEADER: ${{ secrets.header }}
          TG_API_ID: ${{ secrets.TG_API_ID }}
          TG_API_HASH: ${{ secrets.TG_API_HASH }}
        run: ./gradlew -S --no-daemon clean assembleDebug testDebugUnitTest

      - name: Lint
        run: ./gradlew -S --no-daemon lintDebug || echo "Lint skipped"
