name: CI (fishit-player)

on:
  pull_request:
  push:
    branches: [ main, master, develop, feature/** ]

permissions:
  contents: read

jobs:
  build-unit-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - uses: android-actions/setup-android@v3
      - uses: gradle/actions/setup-gradle@v3
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Build + Unit Tests
        env:
          HEADER: ${{ secrets.header }}
          TG_API_ID: ${{ secrets.TG_API_ID }}
          TG_API_HASH: ${{ secrets.TG_API_HASH }}
        run: ./gradlew -S --no-daemon clean assembleDebug testDebugUnitTest

      - name: Lint
        run: ./gradlew -S --no-daemon lintDebug || echo "Lint skipped"
