name: Codex Bot (on-demand)

on:
  workflow_dispatch:
    inputs:
      comment:
        description: 'Optional: /codex Befehl manuell auslösen'
        type: string
        required: false
      gradle_args:
        description: 'Optional: Gradle-Args (z. B. "assembleDebug testDebugUnitTest")'
        type: string
        required: false
  issue_comment:
    types: [created, edited]
  issues:
    types: [opened, edited]
  pull_request_review_comment:
    types: [created, edited]

permissions:
  contents: write
  pull-requests: write
  issues: write

# stabil, unabhängig von ref (Kommentare haben teils keinen ref)
concurrency:
  group: codex-${{ github.run_id }}
  cancel-in-progress: true

jobs:
  gate:
    name: Route command / security gate
    runs-on: ubuntu-latest
    outputs:
      run_codex:  ${{ steps.gate.outputs.run_codex }}
      do_gradle:  ${{ steps.gate.outputs.do_gradle }}
      gradle_args:${{ steps.gate.outputs.gradle_args }}
      issue_no:   ${{ steps.gate.outputs.issue_no }}
    steps:
      - id: gate
        shell: bash
        run: |
          set -euo pipefail
          ev="${{ github.event_name }}"
          body=""
          issue_no=""

          if [[ "$ev" == "workflow_dispatch" ]]; then
            body="${{ inputs.comment || '' }}"
          elif [[ "$ev" == "issue_comment" ]]; then
            body="${{ github.event.comment.body || '' }}"
            issue_no="${{ github.event.issue.number }}"
          elif [[ "$ev" == "pull_request_review_comment" ]]; then
            body="${{ github.event.comment.body || '' }}"
            issue_no="${{ github.event.pull_request.number }}"
          elif [[ "$ev" == "issues" ]]; then
            body="${{ github.event.issue.body || '' }}"
            issue_no="${{ github.event.issue.number }}"
          fi

          # Default flags
          run_codex=false
          do_gradle=false
          args=""

          # Tolerant: /codex irgendwo im Text (case-insensitive)
          if echo "$body" | grep -qi "/codex"; then
            run_codex=true
          fi
          # Dispatch ohne Kommentar → kein codex
          # Dispatch mit Kommentar → codex
          if [[ "$ev" == "workflow_dispatch" && -n "${{ inputs.comment }}" ]]; then
            run_codex=true
          fi

          # Routing für Gradle
          if echo "$body" | grep -qiE '/codex[[:space:]]+build([[:space:]]|$)'; then
            do_gradle=true; args="assembleDebug"
          fi
          if echo "$body" | grep -qiE '/codex[[:space:]]+test([[:space:]]|$)'; then
            do_gradle=true; args="testDebugUnitTest"
          fi
          if echo "$body" | grep -qiE '/codex[[:space:]]+verify-?tdlib([[:space:]]|$)'; then
            do_gradle=true; args="verifyTdlib"
          fi
          if echo "$body" | grep -qiE '/codex[[:space:]]+gradle[[:space:]]+'; then
            do_gradle=true
            args="$(printf '%s\n' "$body" | sed -n 's#.*\/codex[[:space:]]\+gradle[[:space:]]\+##Ip' | head -n1)"
          fi
    
          # Flag --verify irgendwo → Tests
          if $run_codex && echo "$body" | grep -qi -- ' --verify'; then
            do_gradle=true
            if [[ -z "$args" ]]; then args="testDebugUnitTest"; fi
          fi

          # Manuelle Gradle-Args per dispatch
          if [[ "$ev" == "workflow_dispatch" && -n "${{ inputs.gradle_args }}" ]]; then
            do_gradle=true; args="${{ inputs.gradle_args }}"
          fi

          echo "run_codex=$run_codex"   >> "$GITHUB_OUTPUT"
          echo "do_gradle=$do_gradle"   >> "$GITHUB_OUTPUT"
          echo "gradle_args=$args"      >> "$GITHUB_OUTPUT"
          echo "issue_no=$issue_no"     >> "$GITHUB_OUTPUT"

      - name: Debug gate
        run: |
          echo "event=${{ github.event_name }}"
          echo "run_codex=${{ steps.gate.outputs.run_codex }}"
          echo "do_gradle=${{ steps.gate.outputs.do_gradle }}"
          echo "gradle_args=${{ steps.gate.outputs.gradle_args }}"
          echo "issue_no=${{ steps.gate.outputs.issue_no }}"

  ack:
    name: Ack in Thread
    needs: gate
    if: ${{ needs.gate.outputs.run_codex == 'true' && github.event_name != 'workflow_dispatch' && needs.gate.outputs.issue_no != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ needs.gate.outputs.issue_no }}
          body: |
            ✅ **Befehl empfangen.**
            - gradle: `${{ needs.gate.outputs.do_gradle }}`
            - args: `${{ needs.gate.outputs.gradle_args }}`

  codex:
    name: Run Codex Bot
    needs: gate
    if: ${{ needs.gate.outputs.run_codex == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          if [[ -f .github/codex/requirements.txt ]]; then
            pip install -r .github/codex/requirements.txt
          else
            pip install "openai>=1.43.0" "unidiff>=0.7.5" "requests>=2.31.0"
          fi

      - name: Run Codex Bot
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }}
          OPENAI_MODEL_DEFAULT: ${{ vars.OPENAI_MODEL_DEFAULT }}
          OPENAI_REASONING_EFFORT: ${{ vars.OPENAI_REASONING_EFFORT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
          GH_EVENT_NAME: ${{ github.event_name }}
          DISPATCH_COMMENT: ${{ inputs.comment }}
          CODEX_ALLOWLIST: ${{ vars.CODEX_ALLOWLIST }}
        run: python .github/codex/bot.py

  gradle:
    name: Gradle (on-demand: ${{ needs.gate.outputs.gradle_args }})
    needs: gate
    if: ${{ needs.gate.outputs.do_gradle == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
        # fetch-depth 0 optional für Versionierung/patch
          fetch-depth: 0

      - name: Detect AGP / JDK
        id: detect
        shell: bash
        run: |
          set -euo pipefail
          AGP=$(grep -RhoE "com\.android\.tools\.build:gradle[: ]+[\"']([0-9]+\.[0-9]+\.[0-9]+)[\"']" --include="*.gradle*" | sed -E "s/.*['\"]([0-9]+\.[0-9]+\.[0-9]+)['\"].*/\1/" | head -n1 || true)
          JDK=17; if [[ -n "$AGP" ]]; then MAJOR=${AGP%%.*}; if (( MAJOR < 8 )); then JDK=11; fi; fi
          echo "jdk=$JDK" >> "$GITHUB_OUTPUT"

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ steps.detect.outputs.jdk }}
          cache: gradle

      - uses: android-actions/setup-android@v3

      - uses: gradle/actions/setup-gradle@v3
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Fix gradlew permissions
        run: |
          chmod +x ./gradlew || true
          if [[ -f gradlew ]]; then sed -i 's/\r$//' gradlew || true; fi

      - name: Run Gradle
        id: run
        env:
          HEADER: ${{ secrets.header }}
          TG_API_ID: ${{ secrets.TG_API_ID }}
          TG_API_HASH: ${{ secrets.TG_API_HASH }}
        shell: bash
        run: |
          set -o pipefail
          echo "Args: ${{ needs.gate.outputs.gradle_args }}"
          ./gradlew -S --no-daemon --build-cache ${{ needs.gate.outputs.gradle_args }} 2>&1 | tee gradle.log

      - name: Upload artifacts (if assemble/bundle)
        if: contains(needs.gate.outputs.gradle_args, 'assemble') || contains(needs.gate.outputs.gradle_args, 'bundle')
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            **/build/outputs/apk/**/**/*.apk
            **/build/outputs/bundle/**/**/*.aab
            **/build/outputs/mapping/**/mapping.txt
          if-no-files-found: ignore

      - name: Post result to thread
        if: ${{ github.event_name != 'workflow_dispatch' && needs.gate.outputs.issue_no != '' }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ needs.gate.outputs.issue_no }}
          body: |
            🧪 **Gradle ausgeführt**: `${{ needs.gate.outputs.gradle_args }}`
            Status: **${{ job.status }}**
            Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
