name: Codex – Triage (Bot 3)

on:
  issues:
    types: [labeled]
  workflow_dispatch:
    inputs:
      issue:
        description: "Issue-Nummer (bei manuellem Dispatch)"
        required: false
        default: ""

permissions:
  contents: write
  pull-requests: write
  actions: write
  issues: write

concurrency:
  group: codex-triage
  cancel-in-progress: false

jobs:
  triage:
    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'issues' &&
       (github.event.label.name == 'contextmap-error' || github.event.label.name == 'solver-error'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade openai requests

      - name: Export GH_EVENT_NAME & ISSUE_NUMBER
        run: |
          echo "GH_EVENT_NAME=${{ github.event_name }}" >> $GITHUB_ENV
          echo "ISSUE_NUMBER=${{ github.event.inputs.issue }}" >> $GITHUB_ENV

      - name: Run Bot 3 (Triage)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL_DEFAULT: ${{ vars.OPENAI_MODEL_DEFAULT }}
          OPENAI_REASONING_EFFORT: high
          OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }}

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
          GH_EVENT_NAME: ${{ env.GH_EVENT_NAME }}
          ISSUE_NUMBER: ${{ env.ISSUE_NUMBER }}
        run: python .github/codex/bot_triage.py