name: Codex – ContextMap (Bot 1)

on:
  issues:
    types: [opened, edited]
  workflow_dispatch:
    inputs:
      comment:
        description: "/codex … (optional, für manuellen Test)"
        required: false
        default: ""

permissions:
  contents: write
  pull-requests: write
  actions: write
  issues: write

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install minimal deps
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade openai requests

      - name: Prepare env for workflow_dispatch
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "DISPATCH_COMMENT=${{ inputs.comment }}" >> $GITHUB_ENV

      - name: Export GH_EVENT_NAME (for bot)
        run: echo "GH_EVENT_NAME=${{ github.event_name }}" >> $GITHUB_ENV

      - name: Run ContextMap Bot (low)
        env:
          # Map dein Secret -> erwarteter Name
          OPENAI_API_KEY: ${{ secrets.OPEN_API_KEY }}
          OPENAI_MODEL_DEFAULT: ${{ vars.OPENAI_MODEL_DEFAULT }}   # gpt-5
          OPENAI_REASONING_EFFORT: low

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
          GH_EVENT_NAME: ${{ env.GH_EVENT_NAME }}
          DISPATCH_COMMENT: ${{ env.DISPATCH_COMMENT }}
        run: python .github/codex/bot_contextmap.py
